[book]
authors = ["Michael Robert Buche"]
description = "flavio welcomes you"
language = "en"
multilingual = false
src = "src"
title = "f l a v i o"

[output.html]
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[preprocessor.svgbob]
