name: pages
on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install mdbook
        run: cargo install mdbook
      - name: mdbook build
        run: cd docs/ && mdbook build
      - name: pages
        uses: actions/configure-pages@v3
      - name: upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/book/'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
