name: Pages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "Pages"
  cancel-in-progress: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dev
        run: |
          mkdir -p _site/dev/
          cargo doc --release --features fem
          cp -r target/doc/* _site/dev/
          mv _site/dev/flavio/* _site/dev/
  Deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
