name: Publish
on:
  release:
    branches: [ main ]
    types: [ published ]
env:
  CARGO_TERM_COLOR: always
jobs:
  Publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        run: cargo package
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        run: cargo publish
