name: Publish
on:
  pull_request:
    branches: main
  release:
    types: published
env:
  CARGO_TERM_COLOR: always
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Package
        run: cargo package
      - name: Login
        if: github.event_name == 'release'
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        if: github.event_name == 'release'
        run: cargo publish
