name: Test
on:
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  Cargo:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Lint math
        run: cargo clippy --release --features math -- -D warnings
      - name: Lint mechanics
        run: cargo clippy --release --features mechanics -- -D warnings
      - name: Lint constitutive
        run: cargo clippy --release --features constitutive -- -D warnings
      - name: Lint fem
        run: cargo clippy --release --features fem -- -D warnings
      - name: Test math
        run: cargo test --release --features math
      - name: Test mechanics
        run: cargo test --release --features mechanics
      - name: Test constitutive
        run: cargo test --release --features constitutive
      - name: Test fem
        run: cargo test --release --features fem
      - name: Tree
        if: matrix.os == 'ubuntu-latest'
        run: $([[ $(cargo tree --color always --edges normal --features fem | wc -l) -eq 1 ]])
