name: test
on:
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cargo clippy math
        run: cargo clippy --release --features math -- -D warnings
      - name: cargo clippy mechanics
        run: cargo clippy --release --features mechanics -- -D warnings
      - name: cargo clippy constitutive
        run: cargo clippy --release --features constitutive -- -D warnings
      - name: cargo test math
        run: cargo test --release --features math
      - name: cargo test mechanics
        run: cargo test --release --features mechanics
      - name: cargo test constitutive
        run: cargo test --release --features constitutive
  mdbook:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install mdbook
        run: cargo install mdbook
      - name: mdbook build
        run: cd docs/ && mdbook build
